---
title: Publication
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  texts:
    title: Texts
    output: true
  uploads:
    title: Uploads
    output: true
  
tagline: 9th grade publication
description: lorem ipsum
url: https://pixelvoxelboxel.github.io
baseurl: "/ed"
author:
  name: Test
  url: 
  email: test@gmail.com
color-scheme: yellow
permalink: "/:title/"
encoding: utf-8
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
exclude:
- optional
- vendor
- ed..gemspec
- Gemfile
- Gemfile.lock
- backstop_data
- backstop.json
remote_theme: minicomp/ed
